name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.0"
          otp-version: "27.0.0"
          gleam-version: "1.4.0"
          rebar3-version: "3"
          
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Check formatting
        run: mix format --check-formatted

      - name: Install mix_gleam
        run: mix archive.install hex mix_gleam --force

      - name: Get basic project deps
        run: mix deps.get

      - name: Test basic project
        run: mix test

      - name: Gleam test basic project
        run: mix gleam.test
